### PR TITLE
Final submit

### PR DESCRIPTION
**Pull request by Shorya7**
project completed using html and css
this is the frontend of a blogging website

### CODE REVIEW

**Review by khareyash05 — CHANGES_REQUESTED** [review]
Create a folder by your name and then push the files in the folder and then make a PR

**Comment by Shorya7** [comment]
Updated

**Review by khareyash05 — CHANGES_REQUESTED** [review]
Why have you removed the already existing files present in the repo? Kindly revert them and just add your files in your name folder

**Comment by Shorya7** [comment]
Done , all my files are in a single folder of my name and all other folders and files of repo are as it is

**Review by khareyash05 — APPROVED** [review]

**Comment by khareyash05** [comment]
LGTM

**Pull request merged**
